name: Auto Merge
on: [pull_request_target]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MERGE_GITHUB_TOKEN }}
