name: CI
on: push
env:
  CI: true
jobs:
  lint-and-type-check:
    name: Lint & Type-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        name: Install Bun
        with:
          bun-version: 1.1.45
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Lint & Type-Check
        run: bun run concurrently "bun run lint" "bun run type-check"
  Build:
    name: Build
    needs: Lint-and-Type-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        name: Install Bun
        with:
          bun-version: 1.1.45
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
